Traceback (most recent call last):
  File "overturning_time_loop.py", line 82, in <module>
    plotting_functions.overturning_output_plots(dint_latx, dint_laty, dint_interp_latx,dint_interp_laty,t_slice,"atl_so")
  File "/project2/mfj/TatsuM/Projects/ECCO-potential-density-overturning/analysis_package/plotting_functions.py", line 366, in overturning_output_plots
    plt.savefig("./figures/"+basin_name+"_overturning_with_interp"+str(time_slice[0])+"to"+str(time_slice[-1])+".png")
  File "/home/tdmonkman/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/tdmonkman/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/tdmonkman/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/home/tdmonkman/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/home/tdmonkman/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/tdmonkman/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 407, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/home/tdmonkman/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 392, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: './figures/atl_so_overturning_with_interp0to11.png'
